### ISSUE TITLE
Implement `-sync-before` cmdline flag

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#1]
This should allow a user to copy files in to a guest image before boot. Probably like: `transient -sync-before /host/dir:/vm/dir`. It's not obvious to me how you specify the partition within the guest.

We should almost certainly use `virt-copy-in` for this.

**Comment by senofsky** [comment]
This feature would be useful. I would like to take ownership of it.

**Comment by ALSchwalm** [comment]
Closed in #55
