### ISSUE TITLE
Neat project!

### ISSUE THREAD

**Issue by ghost** [ALSchwalm/transient#108]
No issue here. Just wanted to say this project is very neat and more in line with what many of us are missing with TravisCI, Jenkins, Ansible, and others. Thanks for using QEMU!

**Comment by ALSchwalm** [comment]
Thanks for the support! It's definitely been useful for us (@starlab-io) in our test infrastructure.

I'm gonna go ahead and close this, but it's always good to hear that other people/companies are using or interested in the project
