### ISSUE TITLE
Avoid applying `copy-in-before`/`copy-out-after` to all images

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#122]
Currently we apply a given `-copy-in-before` or `-copy-out-after` flag to every `-image` specified. For example:

https://github.com/ALSchwalm/transient/blob/fbb41075fe2c725276b7b1ddd5686b9bebb624cd/transient/transient.py#L164-L169

This is surprising behavior. For now, it is probably ok to copy only to the first `-image`. In the future, we may expand the syntax to allow a user to specify which disk, but that will be a separate issue. The current behavior is almost certainly not desired, though, so changing it to be only the first disk will resolve this.

**Comment by ALSchwalm** [comment]
Also, the documentation should be updated to reflect any change made as a part of fixing this.

**Comment by fpatwa** [comment]
Could you please assign this to me - Thanks!
