### ISSUE TITLE
Support UEFI boot

### ISSUE THREAD

**Issue by benfogle** [ALSchwalm/transient#143]
I have a set of images that require UEFI to boot. Doing so right now requires:

1. Download a copy of OVMF (major distros have binary packages) to get the firmware.
2. Add `-bios /path/to/ovmf` to the qemu command line.
3. Alter `-device scsi-hd,drive=hd0` ==> `-device scsi-hd,drive=hd0,bootindex=0`. Otherwise ovmf might fail to consider the image, or it might try PXE boot first.

3 requires changes to the transient itself. It would be convenient if transient could also do 1 and 2 with the addition of a `-uefi` parameter.

**Comment by benfogle** [comment]
On second thought, maybe it's better to not add a `-uefi` flag. Very, very few vagrant images will boot under UEFI, so it would be a pain to test. Second, if your distro comes with an OVMF package, you can probably just add `-bios OVMF.fd` or similar to the command line. Third: supplying our own firmware is another 2-4MB we're carrying around that most people won't use.

**Comment by ALSchwalm** [comment]
Agreed with your most recent message. I don't think I particularly want to ship an ovmf blob as part of transient. I believe with the merge of #144 I should be able to close this? I'm happy to merge a test for it though.

**Comment by benfogle** [comment]
Yeah, we can close this.
