### ISSUE TITLE
Implement `-sync-after` cmdline flag

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#2]
This should allow a user to copy from in to a guest image after shutdown. Probably like: `transient -sync-after /host/dir:/vm/dir`. It's not obvious to me how you specify the partition within the guest.

We should almost certainly use `virt-copy-out` for this.

**Comment by senofsky** [comment]
This feature would be useful. I would like to take ownership of it.

**Comment by senofsky** [comment]
I'm just about done with this ticket but I want to hammer our some nuances.

When I see the flags `-sync-before`/`-sync-after`, I think that the host directory and the guest directory will be synchronized. I believe this implies that host and guest directories will "merge" together. Naturally, this leads to the possibility of overwriting data if each directory contains a file with the same name.

I think the newer file should be selected given this scenario.

My other option is to break up `-sync-before`/`-sync-after` into `-copy-in-before`, `-copy-in-after`, `-copy-out-before`, and `copy-out-after`, where the commands are more explicit and it's known that the data being copied will overwrite existing data.

Any thoughts on this?

**Comment by ALSchwalm** [comment]
I think I see what you're saying. However, I just read the `sync` here like `rsync`, which does not change the contents of the source directory based on the destination. I'd like to either keep the `-sync-before` and `-sync-after` name or switch to `copy-in-before` and `copy-out-after`. There is no need for `copy-out-before` or `copy-in-after`.

**Comment by senofsky** [comment]
That makes sense.

I will use `-copy-in-before` and `-copy-out-after` and have both use a `source:destination` parameter.
`-copy-in-before` will copy the host directory to the guest directory before starting the VM.
`-copy-out-after` will copy the guest directory to the host directory after stopping the VM.

I _personally_ think this is unambiguous.

**Comment by ALSchwalm** [comment]
Closed in #55
