### ISSUE TITLE
Support creating the guest dir when doing a host shared-directory

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#22]
Right now if you pass `-shared-folder`, the guest directory must already exist or the `sshfs` command will fail. We should create the guest mount point.

**Comment by fpatwa** [comment]
I would like to work on this @ALSchwalm

**Comment by senofsky** [comment]
I'm working with `virt-copy-in` regarding `-sync-before` and `-sync-after` feature. You might be able to use that to create a new directory in the VM.

**Comment by ALSchwalm** [comment]
I see your point @senofsky and I think that's true. But it's probably simpler to just add it to the sshfs setup script here: https://github.com/ALSchwalm/transient/blob/b823137236ad5df7128e57f82d1b526aee8097e5/transient/sshfs.py#L162

We already have to run as a script instead of a single command (the comment there explains why) so we aren't taking the cost of doing another ssh connection or anything like that.

That said, I'm open to using the stuff are working on for this purpose as too if it fits in well. The main benefit to your approach is that we _can't_ have any weird permissions issues or anything inside the guest.

**Comment by willabele** [comment]
I didn't realize there was already an issue for this. #41 should address this problem.
