### ISSUE TITLE
Allow backing image to be specified as a file

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#26]
If you have a disk image already on your filesystem you want to use as the 'base' that the vm images will be built on, you should be able to do that by specifying it in the `-image` flag. Something like: `-image file=/path/to/file`.

**Comment by willabele** [comment]
I can do that!

**Comment by ALSchwalm** [comment]
If you haven't started on this, it might be wise to based it off of the adam-dev branch. I've made some significant changes to stuff over there. I'm just waiting on the merge requests from OSS friday to come in so people don't have to rebase a bunch.

**Comment by willabele** [comment]
I went ahead and reworked it on your branch yesterday. Just waiting for your branch to be merged before finishing up.

**Comment by ALSchwalm** [comment]
Awesome. I'll merge mine when I get home this afternoon. Thanks for working on this.

**Comment by ALSchwalm** [comment]
My stuff is merged.

**Comment by ALSchwalm** [comment]
If you're still interested in doing this, it should probably be done like the other image protocols (e.g. the 'http' one here: https://github.com/ALSchwalm/transient/blob/master/transient/image.py#L236)
