### ISSUE TITLE
Fix bug where invalid flags don't always error 

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#32]
For symmetry with `qemu` transient uses the `-flag` style instead of `--flag`. This is causing some confusion for `argparse`. It seems like it does not trigger an error if you pass a flag that does not exist as long as it shares a prefix with a valid command.

For example `-ssh-foobar` does not error.

**Comment by ALSchwalm** [comment]
Looking at this, I'm not sure it is possible without monkey patching `argparse` or something. We may need to switch to a different commandline parsing implementation. Or we just give up on the qemu-style single dash.

**Comment by senofsky** [comment]
`argparse` also doesn't recognize the `--` separator, correct?

**Comment by ALSchwalm** [comment]
It does, though it doesn't document that fact well. That's why we can pass arbitrary flags after the `--`.

**Comment by senofsky** [comment]
Well then can pass QEMU flags (that only have have a single dash) after the `--` and have transient flags with double dashes, right?

In my _opinion_, symmetry isn't important here, especially if it's causing us a headache and we have a delimiter indicating a separation between transient and qemu flags.

**Comment by ALSchwalm** [comment]
Yes, that is a viable solution. I just wanted to keep the symmetry between QEMU and transient flags. That said, you're right that having that be an easy way to distinguish between them might be good. I think the alternative is that we switch to something like [click](https://click.palletsprojects.com/en/7.x/) that I think will let us do this.

**Comment by ALSchwalm** [comment]
I've discovered that on python 3.6, the repeated `-v` flags don't work as expected. So `-vvv` returns an error, but `-v -v -v` works. I think I'd like to just move away from `argparse`.
