### ISSUE TITLE
Add support for the qemu machine protocol

### ISSUE THREAD

**Issue by dlrobertson** [ALSchwalm/transient#40]
## Summary

Add support for the Qemu Machine Protocol ([QMP]). Knowing the status of the VM seems particularly useful.

## Relevant Links

 - [QMP] wiki
 - [QMP Reference Manual](https://www.qemu.org/docs/master/qemu-qmp-ref.html)
 - The [qmp shell](https://github.com/qemu/qemu/blob/master/scripts/qmp/qmp-shell)

[QMP]: https://wiki.qemu.org/Documentation/QMP

**Comment by ALSchwalm** [comment]
I like this idea

**Comment by ALSchwalm** [comment]
Now supported via the `QmpClient`
