### ISSUE TITLE
Add support for building qcow images with Dockerfile syntax

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#64]
The plan for this is essentially:

Suppose the user has a Imagefile like:

```

FROM scratch
DISK 4GB
PARTITION 0 SIZE 256MB MOUNT /boot
PARTITION 1 MOUNT /
ADD rootfs /
RUN apt-get install grub
RUN grub-install --target=i386-pc /dev/sda
```

This builds a disk with two partitions, one that is 256MB and the other that
is the rest of the 4GB disk. It adds the contents of the directory 'rootfs'
to the partition mounted at / and then instlal grub. This assumes that the 
contents of 'rootfs' are a minimal ubuntu root file system.

To do this (without root) we follow these

1. Create a squashfs of the build directory. This doesn't require root,
and docker does a similar copy when you `docker build .`, so that should
be fine.

2. Create an empty disk of the requested size via dd or qemu-img

3. Spawn QEMU with a kernel/initramfs we have built. And pass the empty
disk as drive 0, and the squashfs as drive 1

4. Connect to the VM (probably via ssh)

5. Inside the VM, use parted (or similar) to partition the empty disk
as requested.

6. Perform the ADD by copying from the squashfs to the newly partitioned
drive

7. chroot in to the partitioned drive and execute the RUN command

8. When all commands are completed, shutdown the VM. The previously empty
disk is now the built image.

Once a 'base' image like this has been built. Other Imagefile files can
be made that just:

```
FROM ubuntu:18.04
RUN apt-get install emacs
```

Just like docker

**Comment by dlrobertson** [comment]
> Inside the VM, use parted (or similar) to partition the empty disk as requested.

It would be cool to provide something close to "raw" `parted` and `dd` commands. This would be particularly useful if you were to target something "non-standard" like `-machine orangepi-pc` see http://www.orangepi.org/Docs/Settingup.html

That being said we could keep `PARITION` simple and then allow some sort of "advanced" configuration with the parted with something like

```
# RK3399-pc image flash
RUN-PREPARE parted $DISK mklabel gpt
RUN-PREPARE parted -a optimal $DISK unit b mkpart idbloader 32768 4128767
RUN-PREPARE parted -a optimal $DISK unit b mkpart uboot 8388608 12582911
...
RUN-PREPARE dd if=./idbloader.img of=${DISK}1 && sync
RUN-PREPARE dd if=./uboot.img of=${DISK}2 && sync
```
