### ISSUE TITLE
Create destination folder for `-copy-in-before` if it does not exist

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#69]
Currently if the user specifies `-copy-in-before somdir:/notexists` then there will be a spew of error output from libguestfs. We should create the directory if it doesn't exist (assuming this is relatively easy)

**Comment by senofsky** [comment]
`-copy-in-before` just uses `virt-copy-in`. According to `virt-copy-in`'s man page:
```
virt-copy-in -a disk.img file|dir [file|dir ...] /destination

You can give one or more filenames and directories on the command line.
Directories are copied in recursively. 
The final parameter must be the destination directory in the disk image
which must be an absolute path starting with a / character.
```

Therefore, `-copy-in-before dir:/dir` with create `/dir/dir` in the VM.
To create just `/dir`, we would use `-copy-in-before dir:/`.

Regarding this issue, is the desire to create the parent directory?
`-copy-in-before somdir:/notexists` creates `/nowexists/somdir`

Or do we desire to not follow the `virt-copy-in` convention and instead create "synced" directories?
`-copy-in-before somedir:/somdir` (where `/somdir` does NOT exist on the guest) creates `/somdir`

**Comment by ALSchwalm** [comment]
I believe the latter is the behavior people would expect. Basically, keeping the same semantics as `cp`.

**Comment by senofsky** [comment]
Sticking with `cp -r` semantics for directories makes sense. I'd like to point out that this only creates the base directory of the given path. If the parents of the non-existent directory don't exist either, then this will still fail:

```
-copy-in-before somdir:/notexists/notexists
```

**Comment by senofsky** [comment]
Since I implemented the original version of this, I'm pretty familiar with the logic.

Would you kindly assign this ticket to me? Thank you!

**Comment by ALSchwalm** [comment]
Done. Regarding your point about nested nonexistant directories, I think failing there would be the expected behavior.

**Comment by senofsky** [comment]
Is this issue still relevant? I've seen a lot of changes, including the removal of `libguestfs` and the introduction of `ImageEditor`.

**Comment by ALSchwalm** [comment]
This is no longer relevant, as we use `scp` to do the copy now.
