### ISSUE TITLE
Make backend files readonly

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#77]
There is a qemu hotkey to commit a 'snapshot' to the backing file. The way we create the frontend images makes this hotkey active, so if a user inadvertently presses 'Ctrl+a s', they will save the changes they've made on the frontend to the backend. We should prevent this by just making the backing files readonly (eg, permission bits 444) when they are created.

**Comment by lilk-bit** [comment]
I'll take this
