### ISSUE TITLE
Documentation for `transient-run` flags needs to be updated

### ISSUE THREAD

**Issue by senofsky** [ALSchwalm/transient#93]
Currently, `configuration._TransientRunConfigSchema` contains 20 possible `transient-run` flags.

The documentation for [run](https://transient.readthedocs.io/en/latest/cli/run/#usage) shows 15 possible `transient-run` flags.

The missing flags are:
 - `-config`
- `-copy-timeout`
- `-qmp-timeout`
- `-ssh-with-serial`
- `qemu-args` (while not a `transient-run` flag, I think we should at least mention what this is and possibly add a link to possible QEMU args)

We should also make sure `test/config-files/comprehensive-config` is up to date with this information as well.

Ultimately, updating 3 sources is a maintenance burden that can quickly lead to information getting out of sync. We should probably think of how to mitigate this burden.

**Comment by ALSchwalm** [comment]
This has been fixed and/or is no longer relevant
