### ISSUE TITLE
Use Reverse-SSHFS mounts for shared folders

### ISSUE THREAD

**Issue by JeffreyMitchellSL** [ALSchwalm/transient#95]
SSHFS and the `sftp-server` executable, which is a dependency of `openssh-server`, both support communications over stdio, allowing us to establish an SSH connection and, through that same connection instead of establishing a new one, use SSHFS to mount one of the host's directories. This has already been done in Bash (https://github.com/rom1v/rsshfs) and Python allows similar piping setups but without requiring named pipes.

Using this approach, we could:
- Cut the total number of SSH sessions for shared folders in half
- Not require the host to run an SSH server
    - Not require the guest to have SSH credentials for the host
    - Avoid errors if the host's SSH server is running on an unexpected port
- Reduce the time it takes shared folders to mount

**Comment by JeffreyMitchellSL** [comment]
I'd like to do this.

**Comment by ALSchwalm** [comment]
I confess, it's not super clear to me from that bash script exactly how that works, but if this is doable without hampering performance I'm definitely in favor of it.

**Comment by ALSchwalm** [comment]
Closed by #100
