### ISSUE TITLE
Make running a transient VM with a emulated TPM easier

### ISSUE THREAD

**Issue by dlrobertson** [ALSchwalm/transient#98]
This may be too much of a niche request, but I think something like `transient run ... --tpm1.2` and `transient run ... --tpm2.0` would be ideal where the tpm1.2 and tpm2.0 devices are backed by [swtpm](https://github.com/stefanberger/swtpm). For various qemu devices like TPMs or Network devices using the tap device driver, the user might have other daemons or setup that needs to be run before the VM starts and/or something that needs to be run after the VM finishes. So the addition of an up and down script would also solve this problem, as the user could use the up/down scripts to start/stop the software tpm (or tap device) and then use the qemu args to add the device.

**Comment by ALSchwalm** [comment]
I don't really follow this. Wouldn't it make sense for users needing a tpm (or any before/after action) to write a shell script like:

```
#!/bin/bash
spawn_swtpm
transient run <transient args> -- -tpmdev <whatever>
kill swtpm
```

How does transient doing the execution of swtpm improve things?

**Comment by dlrobertson** [comment]
Good question. I totally understand that this may be out of the scope of transient, but the up/down script pattern I think would be a common one. As a result, I thought it might be worth supporting

**Comment by ALSchwalm** [comment]
I see your point, but I think it would be better for users to wrap transient than for transient to have this functionality. I'm gonna go ahead and close this.
