### ISSUE TITLE
Switch to using rsync for copying files to guests

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/transient#99]
`scp` does not have a way to preserve symbolic links. This can limit the usefulness of `copy-in-before`, as it will copy the links and significantly bloat the size of the copy on the guest filesystem when the target directory contains many symlinks. We should switch to using `rsync` to avoid this issue. I believe `rsync` accepts pretty much all of the `scp` options, so we should be able to keep the majority of the current logic, I think.

**Comment by senofsky** [comment]
Would you kindly assign this issue to me?
